PUBLISHER = "publisher"
YEAR = "year"
ORIGINAL_YEAR = "originalyear"
ISBN = "isbn"
IMAGE = "image"
TITLE = "title"
AUTHOR = "author"
LANGUAGE = "lang"
LOCATION = "location"
BOOK_LINK = "book-link"
BOOK_LOCATION = "book-location"
TIMESTAMP = "timestamp"

AO3_BASE_URL = "https://archiveofourown.org"